public n
N = TRIM(VPROJECT)
SET DEFA TO C:\ACCOUNT\GL\NCBA\&N\
CLOSE DATABASE

SELECT 1
USE C:\ACCOUNT\GL\NCBA\&N\GLMASTER INDEX C:\ACCOUNT\GL\NCBA\&N\GLMASTER EXCL
INDEX ON KODE TO C:\ACCOUNT\GL\NCBA\&N\GLMASTER
REPLACE ALL TOTEBLN_RP WITH TOTBBLN_RP
REPLACE ALL TOTETRI_RP WITH TOTBTRI_RP
REPLACE ALL TOTETHN_RP WITH TOTBTHN_RP


SELECT 2
USE C:\ACCOUNT\GL\NCBA\&N\GLTRAaku INDEX C:\ACCOUNT\GL\NCBA\&N\GLTRAaku EXCL
INDEX ON VOUCHER TO C:\ACCOUNT\GL\NCBA\&N\GLTRAaku
ZAP

SELECT 3
USE C:\ACCOUNT\GL\NCBA\&N\GLMASTEMP EXCL
ZAP

SELECT 4
USE C:\ACCOUNT\GL\NCBA\&N\accusaha EXCL
index on nomor to accusaha

SELECT 5
USE C:\ACCOUNT\GL\NCBA\&N\ARMASTER EXCL

SELECT 6
USE C:\ACCOUNT\GL\NCBA\&N\ARTRAaku EXCL


* MEMASUKKAN DATA GLMASTER YANG KODE REKENINGNYA < 4 KEDALAM GL-AKUMULASI
SELECT 2
	ZAP
	APPEND FROM C:\ACCOUNT\GL\NCBA\&VPROJECT\GLMASTER
	DELETE ALL FOR LEFT(KODE,1) >= "4" OR LEFT(KODE,1) < "1"
	PACK
	COUNT TO X
	
	FOR I = 1 TO X
	SELECT 2
		GOTO I
		M.KODE = KODE
	SELECT 1
		LOCATE FOR KODE = M.KODE
		M.NILAIRP = TOTbBLN_RP
		M.NILAIDO = TOTbBLN_DO
	SELECT 2
		REPLACE ALL AMOUNT WITH M.NILAIRP FOR KODE = M.KODE
		REPLACE ALL AMOUNTDOL WITH M.NILAIDO FOR KODE = M.KODE
	ENDFOR
					
	REPLACE all voucher with " NER.AWAL"
	REPLACE all TANGTRANS WITH ctod("01-01-2002")
	REPLACE all TANGENTRY WITH ctod("01-01-2002")	
	REPLACE all KETE1 WITH "NERACA AWAL "+dtoc(ctod("01-01-2002"))